import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Tribe",
    description: "Generated by Tribe",
};

const robotoMono = Roboto_Mono({
    variable: "--font-roboto-mono",
    subsets: ["latin"],
});

const rebelGrotesk = localFont({
    src: "../public/fonts/Rebels-Fett.woff2",
    variable: "--font-rebels",
    display: "swap",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            <head>
                <link
                    rel="preload"
                    href="/fonts/Rebels-Fett.woff2"
                    as="font"
                    type="font/woff2"
                    crossOrigin="anonymous"
                />
            </head>
            <body className={`${rebelGrotesk.variable} ${robotoMono.variable} antialiased`}>
                {children}
            </body>
        </html>
    );
}
